// Generated by rstantools.  Do not edit by hand.

/*
    FAIRR is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    FAIRR is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with FAIRR.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_FAIRtwo_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 46> locations_array__ =
  {" (found before start of program)",
  " (in 'FAIRtwo', line 26, column 2 to column 10)",
  " (in 'FAIRtwo', line 27, column 2 to column 10)",
  " (in 'FAIRtwo', line 28, column 2 to column 19)",
  " (in 'FAIRtwo', line 29, column 2 to column 10)",
  " (in 'FAIRtwo', line 30, column 2 to column 20)",
  " (in 'FAIRtwo', line 31, column 2 to column 19)",
  " (in 'FAIRtwo', line 32, column 2 to column 22)",
  " (in 'FAIRtwo', line 35, column 2 to column 20)",
  " (in 'FAIRtwo', line 38, column 4 to line 39, column 56)",
  " (in 'FAIRtwo', line 37, column 17 to line 40, column 3)",
  " (in 'FAIRtwo', line 37, column 2 to line 40, column 3)",
  " (in 'FAIRtwo', line 44, column 2 to column 37)",
  " (in 'FAIRtwo', line 45, column 2 to column 31)",
  " (in 'FAIRtwo', line 46, column 2 to column 31)",
  " (in 'FAIRtwo', line 48, column 2 to column 37)",
  " (in 'FAIRtwo', line 49, column 2 to column 31)",
  " (in 'FAIRtwo', line 50, column 2 to column 31)",
  " (in 'FAIRtwo', line 52, column 2 to column 39)",
  " (in 'FAIRtwo', line 55, column 2 to column 39)",
  " (in 'FAIRtwo', line 3, column 2 to column 17)",
  " (in 'FAIRtwo', line 4, column 9 to column 10)",
  " (in 'FAIRtwo', line 4, column 2 to column 14)",
  " (in 'FAIRtwo', line 5, column 9 to column 10)",
  " (in 'FAIRtwo', line 5, column 2 to column 14)",
  " (in 'FAIRtwo', line 6, column 2 to column 17)",
  " (in 'FAIRtwo', line 9, column 2 to column 16)",
  " (in 'FAIRtwo', line 9, column 17 to column 31)",
  " (in 'FAIRtwo', line 9, column 32 to column 46)",
  " (in 'FAIRtwo', line 10, column 2 to column 16)",
  " (in 'FAIRtwo', line 10, column 17 to column 31)",
  " (in 'FAIRtwo', line 10, column 32 to column 46)",
  " (in 'FAIRtwo', line 11, column 2 to column 28)",
  " (in 'FAIRtwo', line 12, column 2 to column 22)",
  " (in 'FAIRtwo', line 15, column 9 to column 14)",
  " (in 'FAIRtwo', line 15, column 16 to column 21)",
  " (in 'FAIRtwo', line 15, column 2 to column 30)",
  " (in 'FAIRtwo', line 16, column 9 to column 14)",
  " (in 'FAIRtwo', line 16, column 2 to column 23)",
  " (in 'FAIRtwo', line 19, column 4 to column 25)",
  " (in 'FAIRtwo', line 21, column 6 to column 38)",
  " (in 'FAIRtwo', line 20, column 19 to line 22, column 5)",
  " (in 'FAIRtwo', line 20, column 4 to line 22, column 5)",
  " (in 'FAIRtwo', line 18, column 23 to line 23, column 3)",
  " (in 'FAIRtwo', line 18, column 2 to line 23, column 3)",
  " (in 'FAIRtwo', line 35, column 9 to column 14)"};
#include <stan_meta_header.hpp>
class model_FAIRtwo final : public model_base_crtp<model_FAIRtwo> {
private:
  int N;
  Eigen::Matrix<double,-1,1> Y_data__;
  Eigen::Matrix<double,-1,1> Z_data__;
  int H;
  double prior_a1;
  double prior_b1;
  double prior_c1;
  double prior_a2;
  double prior_b2;
  double prior_c2;
  double sigma_scale;
  double sdpar;
  Eigen::Matrix<double,-1,-1> Z_lags_data__;
  Eigen::Matrix<double,-1,1> Y_trim_data__;
  int psi_1dim__;
  Eigen::Map<Eigen::Matrix<double,-1,1>> Y{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> Z{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> Z_lags{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> Y_trim{nullptr, 0};
public:
  ~model_FAIRtwo() {}
  model_FAIRtwo(stan::io::var_context& context__, unsigned int
                random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_FAIRtwo_namespace::model_FAIRtwo";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 20;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 20;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 20;
      stan::math::check_greater_or_equal(function__, "N", N, 0);
      current_statement__ = 21;
      stan::math::validate_non_negative_index("Y", "N", N);
      current_statement__ = 22;
      context__.validate_dims("data initialization", "Y", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      Y_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                   std::numeric_limits<double>::quiet_NaN());
      new (&Y) Eigen::Map<Eigen::Matrix<double,-1,1>>(Y_data__.data(), N);
      {
        std::vector<local_scalar_t__> Y_flat__;
        current_statement__ = 22;
        Y_flat__ = context__.vals_r("Y");
        current_statement__ = 22;
        pos__ = 1;
        current_statement__ = 22;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 22;
          stan::model::assign(Y, Y_flat__[(pos__ - 1)],
            "assigning variable Y", stan::model::index_uni(sym1__));
          current_statement__ = 22;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 23;
      stan::math::validate_non_negative_index("Z", "N", N);
      current_statement__ = 24;
      context__.validate_dims("data initialization", "Z", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      Z_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                   std::numeric_limits<double>::quiet_NaN());
      new (&Z) Eigen::Map<Eigen::Matrix<double,-1,1>>(Z_data__.data(), N);
      {
        std::vector<local_scalar_t__> Z_flat__;
        current_statement__ = 24;
        Z_flat__ = context__.vals_r("Z");
        current_statement__ = 24;
        pos__ = 1;
        current_statement__ = 24;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 24;
          stan::model::assign(Z, Z_flat__[(pos__ - 1)],
            "assigning variable Z", stan::model::index_uni(sym1__));
          current_statement__ = 24;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 25;
      context__.validate_dims("data initialization", "H", "int",
        std::vector<size_t>{});
      H = std::numeric_limits<int>::min();
      current_statement__ = 25;
      H = context__.vals_i("H")[(1 - 1)];
      current_statement__ = 25;
      stan::math::check_greater_or_equal(function__, "H", H, 1);
      current_statement__ = 26;
      context__.validate_dims("data initialization", "prior_a1", "double",
        std::vector<size_t>{});
      prior_a1 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 26;
      prior_a1 = context__.vals_r("prior_a1")[(1 - 1)];
      current_statement__ = 27;
      context__.validate_dims("data initialization", "prior_b1", "double",
        std::vector<size_t>{});
      prior_b1 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 27;
      prior_b1 = context__.vals_r("prior_b1")[(1 - 1)];
      current_statement__ = 28;
      context__.validate_dims("data initialization", "prior_c1", "double",
        std::vector<size_t>{});
      prior_c1 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 28;
      prior_c1 = context__.vals_r("prior_c1")[(1 - 1)];
      current_statement__ = 29;
      context__.validate_dims("data initialization", "prior_a2", "double",
        std::vector<size_t>{});
      prior_a2 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 29;
      prior_a2 = context__.vals_r("prior_a2")[(1 - 1)];
      current_statement__ = 30;
      context__.validate_dims("data initialization", "prior_b2", "double",
        std::vector<size_t>{});
      prior_b2 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 30;
      prior_b2 = context__.vals_r("prior_b2")[(1 - 1)];
      current_statement__ = 31;
      context__.validate_dims("data initialization", "prior_c2", "double",
        std::vector<size_t>{});
      prior_c2 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 31;
      prior_c2 = context__.vals_r("prior_c2")[(1 - 1)];
      current_statement__ = 32;
      context__.validate_dims("data initialization", "sigma_scale", "double",
        std::vector<size_t>{});
      sigma_scale = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 32;
      sigma_scale = context__.vals_r("sigma_scale")[(1 - 1)];
      current_statement__ = 32;
      stan::math::check_greater_or_equal(function__, "sigma_scale",
        sigma_scale, 0);
      current_statement__ = 33;
      context__.validate_dims("data initialization", "sdpar", "double",
        std::vector<size_t>{});
      sdpar = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 33;
      sdpar = context__.vals_r("sdpar")[(1 - 1)];
      current_statement__ = 33;
      stan::math::check_greater_or_equal(function__, "sdpar", sdpar, 0);
      current_statement__ = 34;
      stan::math::validate_non_negative_index("Z_lags", "N - H", (N - H));
      current_statement__ = 35;
      stan::math::validate_non_negative_index("Z_lags", "H + 1", (H + 1));
      current_statement__ = 36;
      Z_lags_data__ = Eigen::Matrix<double,-1,-1>::Constant((N - H), (H + 1),
                        std::numeric_limits<double>::quiet_NaN());
      new (&Z_lags)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(Z_lags_data__.data(), (N -
        H), (H + 1));
      current_statement__ = 37;
      stan::math::validate_non_negative_index("Y_trim", "N - H", (N - H));
      current_statement__ = 38;
      Y_trim_data__ = Eigen::Matrix<double,-1,1>::Constant((N - H),
                        std::numeric_limits<double>::quiet_NaN());
      new (&Y_trim)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(Y_trim_data__.data(), (N - H));
      current_statement__ = 44;
      for (int t = 1; t <= (N - H); ++t) {
        current_statement__ = 39;
        stan::model::assign(Y_trim,
          stan::model::rvalue(Y, "Y", stan::model::index_uni((t + H))),
          "assigning variable Y_trim", stan::model::index_uni(t));
        current_statement__ = 42;
        for (int h = 0; h <= H; ++h) {
          current_statement__ = 40;
          stan::model::assign(Z_lags,
            stan::model::rvalue(Z, "Z", stan::model::index_uni(((t + H) - h))),
            "assigning variable Z_lags", stan::model::index_uni(t),
            stan::model::index_uni((h + 1)));
        }
      }
      current_statement__ = 45;
      psi_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 45;
      psi_1dim__ = (H + 1);
      current_statement__ = 45;
      stan::math::validate_non_negative_index("psi", "H + 1", psi_1dim__);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + 1 + 1 + 1 + 1 + 1;
  }
  inline std::string model_name() const final {
    return "model_FAIRtwo";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_FAIRtwo_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ a1 = DUMMY_VAR__;
      current_statement__ = 1;
      a1 = in__.template read<local_scalar_t__>();
      local_scalar_t__ b1 = DUMMY_VAR__;
      current_statement__ = 2;
      b1 = in__.template read<local_scalar_t__>();
      local_scalar_t__ c1 = DUMMY_VAR__;
      current_statement__ = 3;
      c1 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
             lp__);
      local_scalar_t__ a2 = DUMMY_VAR__;
      current_statement__ = 4;
      a2 = in__.template read<local_scalar_t__>();
      local_scalar_t__ b2 = DUMMY_VAR__;
      current_statement__ = 5;
      b2 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(b1,
             lp__);
      local_scalar_t__ c2 = DUMMY_VAR__;
      current_statement__ = 6;
      c2 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
             lp__);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 7;
      sigma = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> psi =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(psi_1dim__,
          DUMMY_VAR__);
      current_statement__ = 11;
      for (int h = 0; h <= H; ++h) {
        current_statement__ = 9;
        stan::model::assign(psi, ((a1 *
          stan::math::exp((-stan::math::square(((h - b1) / c1)) / 2.0))) +
          (a2 *
          stan::math::exp((-stan::math::square(((h - b2) / c2)) / 2.0)))),
          "assigning variable psi", stan::model::index_uni((h + 1)));
      }
      {
        current_statement__ = 12;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(a1, prior_a1,
                         sigma_scale));
        current_statement__ = 13;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(b1, prior_b1, sdpar));
        current_statement__ = 14;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(c1, prior_c1, sdpar));
        current_statement__ = 15;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(a2, prior_a2,
                         sigma_scale));
        current_statement__ = 16;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(b2, prior_b2, sdpar));
        current_statement__ = 17;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(c2, prior_c2, sdpar));
        current_statement__ = 18;
        lp_accum__.add(stan::math::exponential_lpdf<propto__>(sigma, (1 /
                         sigma_scale)));
        current_statement__ = 19;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(Y_trim,
                         stan::math::multiply(Z_lags, psi), sigma));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_FAIRtwo_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double a1 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      a1 = in__.template read<local_scalar_t__>();
      double b1 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      b1 = in__.template read<local_scalar_t__>();
      double c1 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      c1 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
             lp__);
      double a2 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      a2 = in__.template read<local_scalar_t__>();
      double b2 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      b2 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(b1,
             lp__);
      double c2 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 6;
      c2 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
             lp__);
      double sigma = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 7;
      sigma = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      Eigen::Matrix<double,-1,1> psi =
        Eigen::Matrix<double,-1,1>::Constant(psi_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(a1);
      out__.write(b1);
      out__.write(c1);
      out__.write(a2);
      out__.write(b2);
      out__.write(c2);
      out__.write(sigma);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 11;
      for (int h = 0; h <= H; ++h) {
        current_statement__ = 9;
        stan::model::assign(psi, ((a1 *
          stan::math::exp((-stan::math::square(((h - b1) / c1)) / 2.0))) +
          (a2 *
          stan::math::exp((-stan::math::square(((h - b2) / c2)) / 2.0)))),
          "assigning variable psi", stan::model::index_uni((h + 1)));
      }
      if (emit_transformed_parameters__) {
        out__.write(psi);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ a1 = DUMMY_VAR__;
      current_statement__ = 1;
      a1 = in__.read<local_scalar_t__>();
      out__.write(a1);
      local_scalar_t__ b1 = DUMMY_VAR__;
      current_statement__ = 2;
      b1 = in__.read<local_scalar_t__>();
      out__.write(b1);
      local_scalar_t__ c1 = DUMMY_VAR__;
      current_statement__ = 3;
      c1 = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, c1);
      local_scalar_t__ a2 = DUMMY_VAR__;
      current_statement__ = 4;
      a2 = in__.read<local_scalar_t__>();
      out__.write(a2);
      local_scalar_t__ b2 = DUMMY_VAR__;
      current_statement__ = 5;
      b2 = in__.read<local_scalar_t__>();
      out__.write_free_lb(b1, b2);
      local_scalar_t__ c2 = DUMMY_VAR__;
      current_statement__ = 6;
      c2 = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, c2);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 7;
      sigma = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "a1", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "b1", "double",
        std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "c1", "double",
        std::vector<size_t>{});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "a2", "double",
        std::vector<size_t>{});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "b2", "double",
        std::vector<size_t>{});
      current_statement__ = 6;
      context__.validate_dims("parameter initialization", "c2", "double",
        std::vector<size_t>{});
      current_statement__ = 7;
      context__.validate_dims("parameter initialization", "sigma", "double",
        std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ a1 = DUMMY_VAR__;
      current_statement__ = 1;
      a1 = context__.vals_r("a1")[(1 - 1)];
      out__.write(a1);
      local_scalar_t__ b1 = DUMMY_VAR__;
      current_statement__ = 2;
      b1 = context__.vals_r("b1")[(1 - 1)];
      out__.write(b1);
      local_scalar_t__ c1 = DUMMY_VAR__;
      current_statement__ = 3;
      c1 = context__.vals_r("c1")[(1 - 1)];
      out__.write_free_lb(0, c1);
      local_scalar_t__ a2 = DUMMY_VAR__;
      current_statement__ = 4;
      a2 = context__.vals_r("a2")[(1 - 1)];
      out__.write(a2);
      local_scalar_t__ b2 = DUMMY_VAR__;
      current_statement__ = 5;
      b2 = context__.vals_r("b2")[(1 - 1)];
      out__.write_free_lb(b1, b2);
      local_scalar_t__ c2 = DUMMY_VAR__;
      current_statement__ = 6;
      c2 = context__.vals_r("c2")[(1 - 1)];
      out__.write_free_lb(0, c2);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 7;
      sigma = context__.vals_r("sigma")[(1 - 1)];
      out__.write_free_lb(0, sigma);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"a1", "b1", "c1", "a2", "b2", "c2",
                "sigma"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"psi"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(psi_1dim__)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "a1");
    param_names__.emplace_back(std::string() + "b1");
    param_names__.emplace_back(std::string() + "c1");
    param_names__.emplace_back(std::string() + "a2");
    param_names__.emplace_back(std::string() + "b2");
    param_names__.emplace_back(std::string() + "c2");
    param_names__.emplace_back(std::string() + "sigma");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= psi_1dim__; ++sym1__) {
        param_names__.emplace_back(std::string() + "psi" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "a1");
    param_names__.emplace_back(std::string() + "b1");
    param_names__.emplace_back(std::string() + "c1");
    param_names__.emplace_back(std::string() + "a2");
    param_names__.emplace_back(std::string() + "b2");
    param_names__.emplace_back(std::string() + "c2");
    param_names__.emplace_back(std::string() + "sigma");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= psi_1dim__; ++sym1__) {
        param_names__.emplace_back(std::string() + "psi" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"a1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"c1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"a2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"c2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"psi\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(psi_1dim__) + "},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"a1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"c1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"a2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"b2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"c2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"psi\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(psi_1dim__) + "},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((((1 + 1) + 1) + 1) + 1) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (psi_1dim__);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((((1 + 1) + 1) + 1) + 1) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (psi_1dim__);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_FAIRtwo_namespace::model_FAIRtwo;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_FAIRtwo_namespace::profiles__;
}
#endif
#endif
